version: 0.2
env:
  variables:
    PRX_LAMBDA_CODE_S3_KEY: "lambda/PRX-analytics-ingest-lambda.zip"
    PRX_LAMBDA_CODE_CONFIG_PARAMETERS: "AnalyticsIngestLambdaCodeS3ObjectVersion"
    PRX_LAMBDA_ARCHIVE_BUILD_PATH: "/app/build.zip"
  parameter-store:
    DOCKERHUB_USERNAME: "/prx/DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "/prx/DOCKERHUB_PASSWORD"
    MAXMIND_LICENSE_KEY: "/prx/test/analytics-ingest-lambda/MAXMIND_LICENSE_KEY"
    S3_ACCESS_KEY_ID: "/prx/test/analytics-ingest-lambda/AWS_ACCESS_KEY_ID"
    S3_SECRET_ACCESS_KEY: "/prx/test/analytics-ingest-lambda/AWS_SECRET_ACCESS_KEY"
    CODECOV_TOKEN: "/prx/test/dovetail.prx.org/CODECOV_TOKEN"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "cp env-example .env"
      - "docker-compose build"
      - "docker-compose run test"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
