version: 0.2
env:
  variables:
    PRX_LAMBDA_CODE_S3_KEY: "lambda/PRX-analytics-ingest-lambda.zip"
    PRX_LAMBDA_CODE_CONFIG_PARAMETERS: "AnalyticsIngestLambdaCodeS3ObjectVersion"
    PRX_LAMBDA_ARCHIVE_BUILD_PATH: "/app/build.zip"
  parameter-store:
    AIL_ACCESS_KEY_ID: "/prx/test/analytics-ingest-lambda/AWS_ACCESS_KEY_ID"
    AIL_DEFAULT_REGION: "/prx/test/analytics-ingest-lambda/AWS_DEFAULT_REGION"
    AIL_SECRET_ACCESS_KEY: "/prx/test/analytics-ingest-lambda/AWS_SECRET_ACCESS_KEY"
    CODECOV_TOKEN: "/prx/test/dovetail.prx.org/CODECOV_TOKEN"
phases:
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "cp env-example .env"
      - "echo AWS_ACCESS_KEY_ID=$AIL_ACCESS_KEY_ID >> .env"
      - "echo AWS_DEFAULT_REGION=$AIL_DEFAULT_REGION >> .env"
      - "echo AWS_SECRET_ACCESS_KEY=$AIL_SECRET_ACCESS_KEY >> .env"
      - "docker-compose build"
      - "docker-compose run test"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
